### ISSUE TITLE
Error in loading the plugin

### ISSUE THREAD

**Issue by peppepetra** [intelsdi-x/snap-plugin-publisher-opentsdb#13]
When I try to load the plugin with 

```
snapctl load plugin snap-plugin-publisher-opentsdb
```
I receive the error:
gob: name not registered for interface: "conf_policy_node"

**Comment by sandlbn** [comment]
@peppepetra  looks like you have outdated version of snapd.  Can you run snapd --version and paste output here ?

**Comment by peppepetra** [comment]
Yes you are right, I was using v0.9. I updated snap and the plugin is loaded correctly.
